---
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: '14:00'
    timezone: Europe/Berlin
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  commit-message:
    prefix: "module:"
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: certifi
    versions:
    - "> 2019.11.28"
  - dependency-name: typing-extensions
    versions:
    - "> 3.7.4.1"
