---
apiVersion: v1
kind: Namespace
metadata:
  name: e2e
---
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: e2e
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: foo
